<?xml version="1.0" ?>
<robot name="sia20d_navigation_environment" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find urdf_example)/urdf/open_box_mesh_macro.xacro"/>
	<xacro:include filename="$(find urdf_example)/urdf/color_pallet_macro.xacro"/>
	<xacro:include filename="$(find robotiq_s_model_visualization)/cfg/s-model_mesh_macro.xacro"/>
	<xacro:include filename="$(find motoman_config)/cfg/sia20d_mesh_macro.xacro"/>

	<!-- parameters -->
	<xacro:property name="platform_thickness" value="0.1"/>
	<xacro:property name="window_width" value="0.64"/>
	<xacro:property name="window_length" value="0.32"/>
	<xacro:property name="window_frame_thickness" value="0.10"/>
	<xacro:property name="window_frame_depth" value="1.0"/>
	<xacro:property name="robot_prefix" value=""/>
	<xacro:property name="gripper_prefix" value=""/>

	<!-- instantiating windows -->
	<xacro:window_links prefix="window1" w="${window_width}" l="${window_length}" 
		t="${window_frame_thickness}" d="${window_frame_depth}">
		<xacro:material_blue_block prefix=""/>
		<xacro:material_red_block prefix=""/>
	</xacro:window_links>

	<!-- instantiating robots -->
	<xacro:sia20d_mesh prefix="${robot_prefix}"/>
	<xacro:s-model_mesh prefix="${gripper_prefix}"/>

	<xacro:window_links prefix="window2" w="${window_width}" l="${window_length}" 
		t="${window_frame_thickness}" d="${window_frame_depth}">
		<xacro:material_yellow_block prefix=""/>
		<xacro:material_red_block prefix=""/>
	</xacro:window_links>

	<!-- link definitions -->
	<link name="world_frame"/>

	<!-- joint  definitions -->
	<joint name="world_to_window1" type="fixed">
		<origin xyz="1.0 0 ${0.5*window_length + window_frame_thickness}" rpy="0 1.57 0"/>
		<parent link="world_frame"/>
		<child link="window1_parent_frame"/>
	</joint>

	<joint name="world_to_window2" type="fixed">
		<origin xyz="1.0 0 ${1.5*window_length + 3*window_frame_thickness}" rpy="0 1.57 0"/>
		<parent link="world_frame"/>
		<child link="window2_parent_frame"/>
	</joint>

	<joint name="world_to_robot_base" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="world_frame"/>
		<child link="${robot_prefix}base_link"/>
	</joint>
	
	<joint name="wrist_to_gripper" type="fixed">
		<origin xyz="0 0 0.16" rpy="0 0 0"/>
		<parent link="${robot_prefix}link_t"/>
		<child link="${gripper_prefix}palm"/>
	</joint>
	
</robot>


