collision_object_info:
  id: collision_obj
  frame_id: /world_frame
  link_name: "" # not used
  shape_type: 1 # box 
  l: 0.08
  w: 0.08
  h: 1.0
  x: 1.0
  y: 0.2
  z: 0.5
  rx: 0.0
  ry: 0.0
  rz: 0.0
attached_object_info:
  id: attached_obj
  frame_id: gripper_palm
  link_name: gripper_palm 
  shape_type: 1 # box 
  l: 0.2
  w: 0.24
  h: 0.2
  x: 0.0
  y: 0.0
  z: 0.1
  rx: 0.0
  ry: 0.0
  rz: 0.0
tcp_target_info:
  frame_id: world_frame
  x: 1.0
  y: 0.6
  z: 0.2
  rx: 3.14
  ry: 0.0
  rz: 3.14
